### ISSUE TITLE
v0.0.4 not found

### ISSUE THREAD

**Issue by jakelacey2012** [lenkan/deno-http#1]
Hi thanks for making this I'm hitting a problem whilst trying to install this.

```
NotFound: Cannot resolve module "https://raw.githubusercontent.com/lenkan/deno-http/v0.0.4/src/http" from "/Users/faceless_dev/workspace/go/src/github.com/jakelacey2012/play-with-deno/hello-world/index.ts"
    at maybeError (deno/js/errors.ts:38:12)
    at maybeThrowError (deno/js/errors.ts:26:15)
    at sendSync (deno/js/dispatch.ts:67:5)
    at Object.codeFetch (deno/js/os.ts:40:19)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:512:38)
    at moduleNames.map.name (deno/js/compiler.ts:660:31)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:652:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:114975:117)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:84453:106)
```

Do you know what I could be doing wrong?

**Comment by jakelacey2012** [comment]
the code I have is this 
```
import { listen } from 'https://raw.githubusercontent.com/lenkan/deno-http/v0.0.4/src/http'

listen('127.0.0.1:3050', async (req, res) => {
  const encoder = new TextEncoder('utf8')

  const response = encoder.encode(JSON.stringify({
    request: req
  }))

  await res
    .status(200, 'OK')
    .headers({
      'Content-Type': 'application/json',
      'Content-Length': response.byteLength.toString()
    }).send(body)
})
```

**Comment by lenkan** [comment]
@jakelacey2012 thanks for posting. I made a stupid typo when tagging that version. It should be fixed now. Can you try again?

**Comment by jakelacey2012** [comment]
Wonderful looks like that did the trick. Thanks for looking into it so quickly!
